site_name: horqrux
repo_url: "https://github.com/pasqal-io/horqrux"
repo_name: "horqrux"

nav:
  - horqrux in a nutshell: index.md
  - API: api.md
  - Contribute: CONTRIBUTING.md
  - Code of Conduct: CODE_OF_CONDUCT.md
  - Advanced Features:
    - Differentiation: differentiation.md
    - Variational quantum eigensolver: vqe.md
    - Function fitting and PDE solving with DQC: dqc.md
    - Noisy simulation: noise.md

theme:
  name: material
  features:
  - content.code.annotate
  - navigation.indexes
  - navigation.sections

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: light green
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: light green
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
- admonition  # for notes
- footnotes
- pymdownx.arithmatex: # for mathjax
    generic: true
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences:
    custom_fences:
    - name: python
      class: python
      validator: "!!python/name:markdown_exec.validator"
      format: "!!python/name:markdown_exec.formatter"

plugins:
- search
- section-index
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          filters:
            - "!^_"  # exlude all members starting with _
            - "^__init__$"  # but always include __init__ modules and methods

- mkdocs-jupyter:
    theme: light
- markdown-exec

# To get nice tabs
extra_css:
- css/mkdocstrings.css

# For mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - horqrux
